from typing import Final, final

@final
class FaerDType:
    C32: Final[FaerDType]
    C64: Final[FaerDType]
    F32: Final[FaerDType]
    F64: Final[FaerDType]
    def __eq__(self, /, other: FaerDType |int) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, /, other: FaerDType |int) -> bool: ...
    def __repr__(self, /) -> str: ...

    @property
    def name(self, /) -> str: ...

@final
class FaerMat:
    def __repr__(self, /) -> str: ...
    @property
    def dtype(self, /) -> FaerDType: ...
    @classmethod
    def from_list(cls, /, list: list, dtype: FaerDType = ...) -> FaerMat: ...
    @property
    def shape(self, /) -> tuple[int, int]: ...

def sum_as_string(a: int, b: int) -> str: ...
